// Jiwon Nam
using HealthCatalystHomeTest.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Http;

// main controller to connect with server and database
namespace HealthCatalystHomeTest.Controllers
{
    [RoutePrefix("main")]
    public class SearchController : ApiController
    {
        public IHealthCatalystHomeTestContext db;
        // default constructor using entity framework database
        public SearchController()
        {
            db = new HealthCatalystDBEntities();
        }
        /// <summary>
        /// For Testing DB constructor
        /// </summary>
        /// <param name="testDb"></param>
        public SearchController(IHealthCatalystHomeTestContext testDb)
        {
            db = testDb;
        }
        /// <summary>
        /// get data list by input name
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("search/{name}")]
        public IHttpActionResult Search(string name)
        {     
            List<User> result = db.Users.Where(x => x.LastName == name || x.FirstName == name).ToList();

            if (result.Count == 0)
                return NotFound();

            return Ok(result);
        }
        
        /// <summary>
        /// add data to database
        /// </summary>
        /// <param name="user"></param>
        [HttpPost]
        [Route("add")]
        public IHttpActionResult Add(User user)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

             db.Users.Add(user);
             db.SaveChanges();

            return Ok(user);
        }

        /// <summary>
        /// clear all data in DB
        /// </summary>
        /// <returns></returns>
        [HttpDelete]
        [Route("clear")]
        public IHttpActionResult Clear()
        {
            var all = from c in db.Users select c;
            db.Users.RemoveRange(all);
            db.SaveChanges();

            if (db.Users.Count() != 0)
                return BadRequest("Not Cleared");

            return Ok();
        }

        /// <summary>
        /// auto generate DB data set
        /// </summary>
        [HttpPost]
        [Route("autogen")]
        public IHttpActionResult AutoGenerateDB()
        {
            List<User> autogen = AutoGenerateUser();
            foreach (User user in autogen)
            {
                db.Users.Add(user);
            }
            db.SaveChanges();

            return Ok(autogen);
        }

        /// <summary>
        /// helper method to make general form of string
        /// </summary>
        /// <param name="s"></param>
        /// <returns></returns>
        private string FirstCharUpperForm(string s)
        {
            if (s.Length == 0)
                throw new Exception("Data is empty");

            string result = "";
            int isnumber;
            if (int.TryParse(s.First().ToString(), out isnumber))
                return s;
            else if (s.Length > 1)
                result = s.First().ToString().ToUpper() + s.Substring(1, s.Length - 1);
            else
                result = s.ToUpper();

            return result;
        }

        /// <summary>
        /// private method to add single user
        /// </summary>
        /// <param name="lastname"></param>
        /// <param name="firstname"></param>
        /// <param name="age"></param>
        /// <param name="interests"></param>
        /// <param name="image"></param>
        /// <returns></returns>
        private User AddSingleUser(string lastname, string firstname, int age, string interests, Image image)
        {
            byte[] arr;
            using (MemoryStream ms = new MemoryStream())
            {
                image.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                arr = ms.ToArray();

                return new User
                {
                    LastName = lastname,
                    FirstName = firstname,
                    Age = age,
                    Interests = interests,
                    Image = arr
                };
            }
        }
        /// <summary>
        /// helper method to generate users
        /// </summary>
        /// <returns></returns>
        private List<User> AutoGenerateUser()
        {
            List<User> users = new List<User>();

            string[] lastnames = File.ReadAllLines(AppDomain.CurrentDomain.BaseDirectory + "LastNameExamples.txt");

            string[] firstnames = File.ReadAllLines(AppDomain.CurrentDomain.BaseDirectory + "FirstNameExamples.txt");

            string[] interests = File.ReadAllLines(AppDomain.CurrentDomain.BaseDirectory + "InterestsExamples.txt");

            string[] ages = File.ReadAllLines(AppDomain.CurrentDomain.BaseDirectory + "AgeExample.txt");

            List<byte[]> images = new List<byte[]>();       

            for(int i = 0; i < 31; i++)
            {
                Image temp = Image.FromFile(AppDomain.CurrentDomain.BaseDirectory + "ExamplePictures\\image" + (i % 5 + 1) + ".png");
                byte[] arr;
                using (MemoryStream ms = new MemoryStream())
                {
                    temp.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                    arr = ms.ToArray();
                    images.Add(arr);
                }
            }
            

            for (int i = 0; i < 31; i++) {
                string lastname = lastnames[i];
                string firstname = firstnames[i];
                int age = int.Parse(ages[i]);
                string interest = interests[i];
                users.Add(new User()
                {
                    LastName = lastname,
                    FirstName = firstname,
                    Age = age,
                    Interests = interest,
                    Image = images[i]
                });                            
            }

            for (int i = 0; i < 31; i++)
            {
                string lastname = lastnames[i];
                string firstname = firstnames[30-i];
                int age = int.Parse(ages[i/2]);
                string interest = interests[(i*3)%30];
                users.Add(new User()
                {
                    LastName = lastname,
                    FirstName = firstname,
                    Age = age,
                    Interests = interest,
                    Image = images[30-i]
                });
            }

            return users;
        }

    }
}
